language: go

go:
  - 1.7
  - 1.8
  - 1.9

install:
        - go get github.com/go-playground/overalls
        - go get github.com/mattn/goveralls
        - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

script:
        - $GOPATH/bin/overalls -project=github.com/hiendv/gate -covermode=count -ignore=.git,vendor -debug

after_success:
        - $GOPATH/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci
